In [1]:
import pandas as pd 
import numpy as np

df_2021 = pd.read_excel('data2021.xlsx')
df_2022 = pd.read_excel('data2022.xlsx')
df_2023 = pd.read_excel('data2023.xlsx')
df_2024 = pd.read_excel('data2024.xlsx')

In [2]:
result = pd.concat([df_2021, df_2022, df_2023, df_2024], ignore_index=True)
result.head()

Họ tên         Chương trình  \
0          Nguyễn Minh Quân  Quản trị Kinh doanh   
1             Nguyễn Thu Hà  Quản trị Kinh doanh   
2           Nguyễn Thu Hằng  Quản trị Kinh doanh   
3  Ogunbawo Michael Obadara  Quản trị Kinh doanh   
4          Nguyễn Hà Phương  Quản trị Kinh doanh   

                   Đợt tốt nghiệp        SĐT                       Email  \
0  QĐ 596/QĐ-ĐHFPT ngày 31/5/2021  979505698     quan.minh.524@gmail.com   
1  QĐ 596/QĐ-ĐHFPT ngày 31/5/2021  934486007  thuha.nguyen1911@gmail.com   
2  QĐ 596/QĐ-ĐHFPT ngày 31/5/2021  982797584  Hangthng16061999@gmail.com   
3  QĐ 596/QĐ-ĐHFPT ngày 31/5/2021  987123643                         NaN   
4  QĐ 596/QĐ-ĐHFPT ngày 31/5/2021  938902069     your.stefaani@gmail.com   

                    Nơi làm việc hiện tại          Vị trí công việc  \
0                                     NaN                       NaN   
1                                    IMAP           English Teacher   
2          Eurowindow Joint Stock Company  Digital Marketing Expert   
3  Sao Viet import - export & trading jsc            Đào tạo nội bộ   
4                          Viettel Ha Noi         Quản lý văn phòng   

  Việc đang làm có liên quan tới ngành học không? Khoảng lương hiện tại  \
0                                             NaN                   NaN   
1                                           Không                 10-20   
2                                              Có                 30-40   
3                                              Có                 10-20   
4                                              Có                 20-30   

  Trong lúc còn đang học, anh chị có việc làm thêm không?  \
0                                                NaN        
1                                                 Có        
2                                              Không        
3                                                 Có        
4                                                 Có        

  Công việc đó có liên quan tới ngành học không?  \
0                                            NaN   
1                                             Có   
2                                          Không   
3                                             Có   
4                                          Không   

  Anh chị đã chuyển việc mấy lần? Khoảng lương của công việc đầu tiên  
0                             NaN                                 NaN  
1                               4                                 0-5  
2                               5                                5-10  
3                               4                               10-20  
4                               1                                5-10

In [3]:
result.describe(include='all')

Họ tên         Chương trình               Đợt tốt nghiệp  \
count                 1026                 1026                         1026   
unique                 895                   11                           10   
top     Nguyễn Thị Lan Anh  Công nghệ thông tin  QĐ94/QĐ-ĐHFPT ngày 9/2/2022   
freq                     4                  355                          147   

                 SĐT     Email Nơi làm việc hiện tại Vị trí công việc  \
count   1.007000e+03       918                   725              727   
unique  9.300000e+02       846                   433              282   
top     8.494558e+10  Không có             FREELANCE        FREELANCE   
freq    2.000000e+00        15                    90               92   

       Việc đang làm có liên quan tới ngành học không? Khoảng lương hiện tại  \
count                                              644                   635   
unique                                               8                    51   
top                                                 Có                 10-20   
freq                                               411                    92   

       Trong lúc còn đang học, anh chị có việc làm thêm không?  \
count                                                 613        
unique                                                  6        
top                                                    Có        
freq                                                  370        

       Công việc đó có liên quan tới ngành học không?  \
count                                             603   
unique                                              8   
top                                                Có   
freq                                              280   

        Anh chị đã chuyển việc mấy lần? Khoảng lương của công việc đầu tiên  
count                               603                                 604  
unique                               20                                  30  
top                                   2                                5-10  
freq                                164                                  81

In [4]:
# result = result.drop(columns=['ĐT', 'Email'])

True/False data

In [5]:
result['Trong lúc còn đang học, anh chị có việc làm thêm không?'].unique()

array([nan, 'Có', 'Không', 'có', 'không', 'Không ', 'Khong'], dtype=object)

In [6]:
result['Trong lúc còn đang học, anh chị có việc làm thêm không?']= result['Trong lúc còn đang học, anh chị có việc làm thêm không?'].replace("Khong", "Không")

In [7]:
result['Việc đang làm có liên quan tới ngành học không?'].unique()

array([nan, 'Không', 'Có', 0, 'Đúng ngành đào tạo', 'có', 'không',
       'Không liên quan đến ngành đào tạo', 'Không '], dtype=object)

In [8]:
result['Công việc đó có liên quan tới ngành học không?'].unique()

array([nan, 'Có', 'Không', 'có', 'không', 0, 1, 2, 4], dtype=object)

In [9]:
columns_to_capitalize = ['Việc đang làm có liên quan tới ngành học không?', 'Trong lúc còn đang học, anh chị có việc làm thêm không?', 'Công việc đó có liên quan tới ngành học không?']
for column in columns_to_capitalize:
    result[column] = result[column].str.strip().str.replace(r'\s+', ' ', regex=True).str.title()
    result['Việc đang làm có liên quan tới ngành học không?'] = result['Việc đang làm có liên quan tới ngành học không?'].replace({
    'Đúng Ngành Đào Tạo': 'Có',
    'Không Liên Quan Đến Ngành Đào Tạo': 'Không'
})

Range salary

In [10]:
result['Khoảng lương của công việc đầu tiên'].unique()

array([nan, '0-5', '5-10', '10-20', 'Không tiết lộ', '5tr-10tr', '0-5tr',
       '10tr-20tr', '5tr - 10tr', '< 5tr', '10tr - 20tr', '5-10tr',
       '10-20tr', '0 - 5', '0 > 5', '6 > 10 ', '10 > 15 ', '20tr - 30tr',
       '20-30tr', '10-15 tr', '10-20 triệu', '7 > 12 ', '10--20', '5--10',
       '<5', 0, '4 > 7', '5 > 10 ', '5 > 7', '7tr-12tr', '5tr'],
      dtype=object)

In [11]:
result['Khoảng lương hiện tại'].unique()

array([nan, '10-20', '30-40', '20-30', '5-10', '40-100', 'Không tiết lộ',
       '10tr-20tr', '20tr-30tr', '30tr-40tr', '20tr -30tr', '10tr - 20tr',
       '10-20 triệu', '20-30 triệu', '30-40 triệu',
       '21 - 30 triệu VNĐ/tháng', '15 - 20 triệu VNĐ/tháng',
       '10 - 15 triệu VNĐ/tháng', '16 - 20 triệu VNĐ/tháng',
       'Vì lý do bảo mật nên không tiết lộ', '15 - 20 triệu/tháng',
       '5tr - 10tr', '5-10 triệu', '5tr-10tr', '> 30tr', '0-5', '10-20tr',
       '5-10tr', '10 - 20 triệu tháng', '8-10', '13-17', '60-80',
       '10-20 ', '>30', '20--30', '10--20', '5--10', 16, 12, 30, 10, 7,
       13, 20, 9, 5, '15 > 20', '10>15', '10 > 15', '5 > 10',
       '$3000-$5000', '< 5tr'], dtype=object)

In [12]:
# # Hàm chuẩn hóa
# def normalize_value(value):
#     if isinstance(value, str):
#         value = value.replace(" ", "").replace("VNĐ/tháng", "").replace("tháng", "").replace(
#             "triệu/tháng", "").replace("triệu", "").replace("tr", "").replace(">", "-").replace(
#                 "<", "-").replace("--", "-").replace("-5", "0-5").replace("-30", "30-40")

#         # Nếu giá trị là dạng a-b
#         if '-' in value:
#             parts = value.split('-')
#             if len(parts) == 2:
#                 a, b = parts
#                 a, b = int(a) if a.isdigit() else None, int(b) if b.isdigit() else None
                
#                 # Chuyển đổi các khoảng về đúng dạng
#                 if a is not None and b is not None:
#                     if a < 5:
#                         return '0-5'
#                     elif 5 <= a < 10 or 5 <= b < 10:
#                         return '5-10'
#                     elif 10 <= a < 20 or 10 <= b < 20:
#                         return '10-20'
#                     elif 20 <= a < 30 or 20 <= b < 30:
#                         return '20-30'
#                     elif 30 <= a < 40 or 30 <= b < 40:
#                         return '30-40'
#                     elif b >= 40:
#                         return '40-100'
        
#     if isinstance(value, (int, float)) and not np.isnan(value):
#             num_value = int(value)
#             if 0 <= num_value < 5:
#                 return '0-5'
#             elif 5 <= num_value < 10:
#                 return '5-10'
#             elif 10 <= num_value < 20:
#                 return '10-20'
#             elif 20 <= num_value < 30:
#                 return '20-30'
#             elif 30 <= num_value < 40:
#                 return '30-40'
#             elif num_value >= 40:
#                 return '40-100'         
    
#     return np.nan  

# # Áp dụng hàm chuẩn hóa cho các cột
# result['Khoảng lương hiện tại'] = result['Khoảng lương hiện tại'].apply(normalize_value)
# result['Khoảng lương của công việc đầu tiên'] = result['Khoảng lương của công việc đầu tiên'].apply(normalize_value)


In [13]:
import numpy as np
import pandas as pd
import re

def clean_salary_range(x):
    # Handle NaN values
    if pd.isna(x):
        return np.nan
    
    # Convert to string
    x = str(x).lower().replace(' ', '')
    
    # Remove Vietnamese currency and extra characters
    x = x.replace('tr', '').replace('triệu', '').replace('vnđ/tháng', '')
    
    # Special cases
    if x in ['khôngtiếtlộ', 'vílídobaomậtnênkhôngtiếtlộ']:
        return np.nan
    
    # Handle comparison ranges
    if '>' in x:
        x = x.replace('>', '').strip()
        try:
            val = float(x)
            return '40-100' if val >= 30 else np.nan
        except:
            return np.nan
    
    if '<' in x:
        x = x.replace('<', '').strip()
        try:
            val = float(x)
            return '0-5' if val <= 5 else np.nan
        except:
            return np.nan
    
    # Remove any double hyphens or extra symbols
    x = x.replace('--', '-')
    
    # Try to extract numeric ranges
    match = re.findall(r'(\d+)[-]?(\d+)?', x)
    
    if match:
        start = float(match[0][0])
        end = float(match[0][1]) if match[0][1] else start
        
        # Standardize ranges
        if end <= 5:
            return '0-5'
        elif 5 < end <= 10:
            return '5-10'
        elif 10 < end <= 20:
            return '10-20'
        elif 20 < end <= 30:
            return '20-30'
        elif 30 < end <= 40:
            return '30-40'
        elif end > 40:
            return '40-100'
    
    # If no match found, try direct numeric conversion
    try:
        val = float(x)
        if val <= 5:
            return '0-5'
        elif 5 < val <= 10:
            return '5-10'
        elif 10 < val <= 20:
            return '10-20'
        elif 20 < val <= 30:
            return '20-30'
        elif 30 < val <= 40:
            return '30-40'
        elif val > 40:
            return '40-100'
    except:
        return np.nan
    
    return np.nan

result['Khoảng lương hiện tại'] = result['Khoảng lương hiện tại'].apply(clean_salary_range)
result['Khoảng lương của công việc đầu tiên'] = result['Khoảng lương của công việc đầu tiên'].apply(clean_salary_range)

In [14]:
result['Đợt tốt nghiệp'].unique()

array(['QĐ 596/QĐ-ĐHFPT ngày 31/5/2021',
       'QĐ1283/QĐ-ĐHFPT ngày 04/11/2021', 'QĐ94/QĐ-ĐHFPT ngày 9/2/2022',
       'QĐ số 415/QĐ-ĐHFPT ngày 17/05/2022',
       'QĐ 924/QĐ-ĐH FPT ngày 13/10/2022',
       'QĐ 37/QĐ-ĐH FPT ngày 12/1/2023',
       'QĐ 574/QĐ-ĐH FPT ngày 31/5/2023',
       'QĐ 1060/QĐ-ĐHFPT ngày 09/10/2023',
       'QĐ 127/QĐ-ĐHFPT ngày 31/01/2024',
       'QĐ 588/QĐ-ĐHFPT ngày 31/05/2024'], dtype=object)

In [15]:
result['Đợt tốt nghiệp'] = result['Đợt tốt nghiệp'].replace({

    'QĐ 596/QĐ-ĐHFPT ngày 31/5/2021' : '2021-05',
       'QĐ1283/QĐ-ĐHFPT ngày 04/11/2021' : '2021-11', 
       'QĐ94/QĐ-ĐHFPT ngày 9/2/2022': '2022-05',
       'QĐ số 415/QĐ-ĐHFPT ngày 17/05/2022': '2022-05',
       'QĐ 924/QĐ-ĐH FPT ngày 13/10/2022': '2022-11',
       'QĐ 37/QĐ-ĐH FPT ngày 12/1/2023': '2023-05',
       'QĐ 574/QĐ-ĐH FPT ngày 31/5/2023': '2023-05',
       'QĐ 1060/QĐ-ĐHFPT ngày 09/10/2023': '2023-11',
       'QĐ 127/QĐ-ĐHFPT ngày 31/01/2024': '2024-05',
       'QĐ 588/QĐ-ĐHFPT ngày 31/05/2024': '2024-05'    
        })

In [16]:
result['Anh chị đã chuyển việc mấy lần?'].unique()

array([nan, 4, 5, 1, 2, 0, 3, 8, '2 lần', 'Chưa lần nào', '3 lần',
       'Chưa chuyển.', 'Chưa lần nào ', 6, '1 lần', 22, 'không',
       '2-3 lần', 7, 10, 'Không tiết lộ'], dtype=object)

In [17]:
result['Anh chị đã chuyển việc mấy lần?'] = result['Anh chị đã chuyển việc mấy lần?'].replace({

    " lần": "",
    22: 2,
    'Chưa lần nào ': 0,
    "1 lần": 1, 
    'Chưa lần nào': 0,
    "2-3 lần"  : 3,
    'không': 0,
    '2 lần': 2,
    '3 lần': 3,
    'Chưa chuyển.': 0,
    'Không tiết lộ': np.nan
        })

C:\Users\NGUYEN TIEN THINH\AppData\Local\Temp\ipykernel_11552\2532753512.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  result['Anh chị đã chuyển việc mấy lần?'] = result['Anh chị đã chuyển việc mấy lần?'].replace({


In [18]:
result['Chương trình'].unique()

array(['Quản trị Kinh doanh', 'Quản trị Marketing',
       'Thiết kế đồ họa và Kỹ thuật số', 'Top-up IT',
       'Quản trị kinh doanh', 'Công nghệ thông tin', 'MKT', 'QTKD',
       'QT MARKETING', 'QT SỰ KIỆN', 'QT TRUYỀN THÔNG'], dtype=object)

In [19]:
result['Chương trình'] = result['Chương trình'].replace({
    'MKT': 'Business',
    'QTKD': 'Business',
    'QT MARKETING': 'Business',
    'Công nghệ thông tin': 'IT',
    'Thiết kế đồ họa và Kỹ thuật số': 'Design',
    'Quản trị Kinh doanh': 'Business',
    'Quản trị kinh doanh': 'Business',
    'Quản trị Marketing': 'Business',
    'QT SỰ KIỆN': 'Business',
    'Top-up IT': 'IT',
    'QT TRUYỀN THÔNG': 'Business',
})

In [20]:
# result = result.drop(columns=['Họ tên'])

In [21]:
result['Vị trí công việc'].describe()

count           727
unique          282
top       FREELANCE
freq             92
Name: Vị trí công việc, dtype: object

In [22]:
result['Vị trí công việc'] = result['Vị trí công việc'].str.lower()
result['Vị trí công việc'] = result['Vị trí công việc'].str.strip()

In [23]:
result['Vị trí công việc'].unique()

array([nan, 'english teacher', 'digital marketing expert',
       'đào tạo nội bộ', 'quản lý văn phòng',
       'nhân viên phòng kinh doanh - thương mại',
       'chuyên viên tư vấn toàn thời gian', 'kocs', 'leader sales',
       'sale representative', 'account', 'purchasing',
       'influencer marketing consultant', 'assistant manager',
       'branding executive', 'quản lý', 'freelance', 'freelancer',
       'support staff', 'junior business intelligence analyst',
       'academic administration officer', 'bank clerk',
       'onboarding employee', 'youtube content creator', 'marketing',
       'business development', 'kinh doanh', 'sale', 'staff', 'banker',
       'tổ chức sự kiện', 'thất nghiệp', 'sourcing specialist',
       'cán bộ tuyển sinh', 'visual merchandiser - nhân viên trưng bày',
       'graphic designer', 'marketing executive', '2d artist',
       'communications director', 'ui/ux design', 'qa tester',
       'quality control', 'lập trình viên', 'fullstack',
       'mo

In [24]:
result['Vị trí công việc'] = result['Vị trí công việc'].replace({
    # Ngành Truyền thông và Tiếp thị
    'communications officer': 'Marketing',
    'public affairs officer': 'Marketing',
    'internal communications specialist': 'Marketing',
    'auditor': 'Marketing',
    'customer service officer': 'Marketing',
    'event coordinator': 'Marketing',
    'marketing staff': 'Marketing',
    'marketing specialist': 'Marketing',
    'marketing executive': 'Marketing',
    'marketing assistant': 'Marketing',
    'marketing analyst': 'Marketing',
    'marketing designer': 'Marketing',
    'digital marketing': 'Marketing',
    'content marketing': 'Marketing',
    'seo marketing': 'Marketing',
    'tiktok operation coordinator': 'Marketing',
    'tiktok top celeb creator management': 'Marketing',
    'marketing manager': 'Marketing',
    'nhân viên marketing': 'Marketing',
    'quản lý fanpage': 'Marketing',
    'marketing intern': 'Marketing',
    'marketing': 'Marketing',
    'content': 'Marketing',
    'content creator': 'Marketing',
    'content social': 'Marketing',
    'brand marketing': 'Marketing',
    'digital marketing expert': 'Marketing',
    'influencer marketing consultant': 'Marketing',
    'trưởng phòng mkt': 'Marketing',
    'media': 'Marketing',
    'trưởng phòng marketing': 'Marketing',
    'chuyên viên tư vấn toàn thời gian': 'Marketing',
    'youtube content creator': 'Marketing',
    'market analyst': 'Marketing',
    'biên tập viên social': 'Marketing',
    'sale marketing': 'Marketing',
    'nhân viên truyền thông': 'Marketing',
    'marketer': 'Marketing',
    'marketing excutive': 'Marketing',
    'digital maketing executive': 'Marketing',
    'digital marketing executive': 'Marketing',
    'marketing ads': 'Marketing',

    # Ngành Kinh doanh và Quản lý khách hàng
    'sales': 'Sales',
    'telesales': 'Sales',
    'sale': 'Sales',
    'salesman': 'Sales',
    'sale excutive': 'Sales',
    'sale online': 'Sales',
    'sales specialist': 'Sales',
    'nhân viên kinh doanh': 'Sales',
    'quản lý bán hàng': 'Sales',
    'educational consulting (sale/telesale)': 'Sales',
    'trưởng phòng khcn': 'Sales',
    'insurance specialists': 'Sales',
    'personal customer relationship': 'Sales',
    'sale specialist': 'Sales',
    'e-commerce': 'Sales',
    'kinh doanh': 'Sales',
    'key account manager': 'Sales',
    'account manager': 'Sales',
    'life portfolio manager & assistant manager': 'Sales',
    'account': 'Sales',
    'chuyên viên tư vấn đầu tư': 'Sales',
    'sale representative': 'Sales',
    'leader sales': 'Sales',
    'purchasing': 'Sales',
    'nhân viên khcn': 'Sales',
    'nhân viên phòng kinh doanh - thương mại': 'Sales',
    'guest ambassador':'Others',
    'vice head of sales': 'Sales',
    'accountant': 'Sales',
    'kế toán': 'Sales',
    'customer service representative': 'Sales',
    'procurements': 'Sales',
    'customer opeartion specialist': 'Sales',
    'sale executive':'Sales',
    'sales executive':'Sales',
    'sap erp consultant': 'Sales',

    # Ngành Công nghệ thông tin và Phát triển phần mềm
    'developer': 'Developer',
    'software engineer': 'Developer',
    'android developer': 'Developer',
    'auto developer': 'Developer',
    'backend developer': 'Developer',
    'dev front-end': 'Developer',
    'ai engineer': 'Developer',
    'front-end developer': 'Developer',
    'back-end developer': 'Developer',
    'full stack developer': 'Developer',
    'ios developer': 'Developer',
    'mobile developer': 'Developer',
    'unity developer': 'Developer',
    'web developer': 'Developer',
    'be developer': 'Developer',
    'am (bridge engineer)': 'Developer',
    'unity dev': 'Developer',
    'tester': 'Infrastructure & Operations',
    'automation tester': 'Infrastructure & Operations',
    'manual tester': 'Infrastructure & Operations',
    'qa tester': 'Infrastructure & Operations',
    'software testing engineer': 'Infrastructure & Operations',
    'software enginer': 'Developer',
    'devops': 'Developer',
    'thiết kế & vận hành game': 'Developer',
    'backend': 'Developer',
    'back-end': 'Developer',
    'back end developer': 'Developer',
    'lập trình viên': 'Developer',
    'fullstack': 'Developer',
    'moble developer': 'Developer',
    'junior game dev': 'Developer',
    'frontent developer': 'Developer',
    'junior dev untiy': 'Developer',
    'kĩ sư phần mềm': 'Developer',
    'fe dev': 'Developer',
    'dev fullstack': 'Developer',
    'dev backend': 'Developer',
    'fe dev': 'Developer',
    'dev': 'Developer',
    'rpa developer': 'Developer',
    'software development engineer': 'Developer',
    'software developer': 'Developer',
    'upper middle developer': 'Developer',
    'it system admin': 'Infrastructure & Operations',
    'it officer': 'Infrastructure & Operations',
    'kĩ sư chất lượng phần mềm': 'Infrastructure & Operations',
    'chuyên viên giám sát hệ thống': 'Infrastructure & Operations',
    'system development and operations assurance specialist': 'Infrastructure & Operations',
    'cloud operation engineer': 'Infrastructure & Operations',
    'data engineer': 'Infrastructure & Operations',
    'operation admin': 'Infrastructure & Operations',
    'technical specialist': 'Infrastructure & Operations',
    'vận hành mạng': 'Infrastructure & Operations',
    'mmo': 'Sales',
    'network system adminstrator': 'Administration & Support',
    'process quality assurance': 'Infrastructure & Operations',
    'software testing officer': 'Infrastructure & Operations',
    'rpa': 'Infrastructure & Operations',
    'it field': 'Infrastructure & Operations',
    'business analyst': 'Infrastructure & Operations',
    'business assistant':'Administration & Support',
    'junior business intelligence analyst': 'Infrastructure & Operations',
    'ba': 'Infrastructure & Operations',
    'business analyst trainee': 'Infrastructure & Operations',
    'business development': 'Infrastructure & Operations',
    'business employee': 'Infrastructure & Operations',
    'business analyst and market research': 'Infrastructure & Operations',
    'đào tạo nội bộ': 'Infrastructure & Operations',
    'tester, game operation, web event pic, esports operation': 'Infrastructure & Operations',
    'quality control': 'Infrastructure & Operations',
    'production cotrol': 'Infrastructure & Operations',
    'viên chức trung tâm tích hợp dữ liệu': 'Infrastructure & Operations',
    'intern hr': 'Administration & Support',

    # Ngành Thiết kế và Đồ họa
    'designer': 'Graphic Design',
    'graphic designer': 'Graphic Design',
    '3d designer': 'Graphic Design',
    '2d animator': 'Graphic Design',
    'marketing designer': 'Graphic Design',
    'pixel artist / mograph designer': 'Graphic Design',
    'junior designer': 'Graphic Design',
    'ui/ux designer': 'Graphic Design',
    'graphic designer & editor': 'Graphic Design',
    'graphic designer - product designer - multimedia designer': 'Graphic Design',
    'graphic designer, project manager': 'Graphic Design',
    '2d artist': 'Graphic Design',
    'ui/ux design': 'Graphic Design',
    'graphic designer/ editor': 'Graphic Design',
    'motion graphic designer': 'Graphic Design',
    'editor': 'Graphic Design',
    'creative designer': 'Graphic Design',
    'ux designer': 'Graphic Design',
    'agency - design apartment': 'Graphic Design',
    'designer and editor': 'Graphic Design',

    # Ngành Hành chính và Hỗ trợ
    'hr assistant': 'Administration & Support',
    'academic administration officer': 'Administration & Support',
    'officer, hr business partner': 'Administration & Support',
    'procurement assistant': 'Administration & Support',
    'product assistant': 'Administration & Support',
    'customer service': 'Administration & Support',
    'customer support': 'Administration & Support',
    'data entry specialist': 'Administration & Support',
    'office staff': 'Administration & Support',
    'business development trainee': 'Administration & Support',
    'supervisor': 'Administration & Support',
    'support staff': 'Administration & Support',
    'quality assurance': 'Administration & Support',
    'input specialist': 'Administration & Support',
    'technical support': 'Administration & Support',
    'hr':'Administration & Support',
    'assistant manager':'Administration & Support',
    'admission officer':'Administration & Support',
    'admissions consultant':'Administration & Support',
    'admissions consultant officer':'Administration & Support',
    'cán bộ tuyển sinh':'Administration & Support',
    'sourcing specialist':'Administration & Support',
    'trợ lý':'Administration & Support',
    'kiểm soát nội bộ':'Administration & Support',
    'phát triển văn hoá & truyền thông nội bộ':'Administration & Support',
    'startup': 'Freelance',
    'sub-leader mobile department':'Administration & Support',
    'technical consultant':'Administration & Support',
    'personal customer specialist':'Administration & Support',
    'human resource staff':'Administration & Support',
    'driver operations associate':'Administration & Support',

    # Ngành Quản lý dự án
    'executive': 'Executive',
    'project manager': 'Executive',
    'co-founder and director': 'Executive',
    'life portfolio manager': 'Executive',
    'quản lý': 'Executive',
    'leader': 'Executive',
    'manager': 'Executive',
    'branding executive': 'Executive',
    'account executive': 'Executive',
    'quản lý văn phòng': 'Executive',
    'ceo': 'Executive',
    'communications director': 'Executive',
    'trưởng phòng': 'Executive',
    'trưởng nhóm kỹ thuật': 'Executive',
    'cán bộ phát triển ứng dụng': 'Executive',
    'trưởng phòng phát triển sản phẩm': 'Executive',
    'giám đốc điều hành': 'Executive',
    'quản lý văn phòng' : 'Executive',
    'cán bộ văn hóa': 'Executive',
    'giám đốc': 'Executive',
    'director': 'Executive',
    'cán bộ': 'Executive',
    'communication executive': 'Executive',
    'làm chủ công việc kinh doanh': 'Executive',

    # Ngành Giáo dục và Giảng dạy    
    'english teacher/part-time teaching assistant':'Others',
    'giảng viên it':'Others',
    'english teacher':'Others',
    'kocs':'Others',
    'english translater':'Others',
    'couting sky':'Others',
    'master of ceremonies (mc)':'Others',

    # Ngành Dịch vụ tự do
    'staff': 'Staff',
    'undisclosed': 'Undisclosed',
    'freelance': 'Freelance',
    'freelancer': 'Freelance',
    'freelance business': 'Freelance',
    'freelance designer': 'Freelance',
    'fresher fullstack': 'Freelance',
    'kinh doanh tự do': 'Freelance',
    'về nước': 'Undisclosed',
    'import - export staff':'Others',
    'hotel general manager': 'Others',  
    'phó giám đốc phụ trách tiệc cưới': 'Others',  
    'internship': 'Staff',
    'employee':'Staff',
    'onboarding employee':'Staff',
    'banker': 'Others',
    'tổ chức sự kiện':'Others',
    'đào tạo':'Others',
    'nhân viên hành chính': 'Staff',
    'bank clerk': 'Sales',
    'nhân viên': 'Staff',
    'import-export staff': 'Staff',
    'fresher': 'Staff',
    'intern': 'Staff',
    'staff': 'Staff',
    'trưởng phòng kt': 'Executive',
    'giám đốc doanh nghiệp': 'Executive',
    'coo, co founder': 'Executive',
    'giám đốc phát triển': 'Executive',
    'trưởng phòng thiết kế': 'Executive',
    'thất nghiệp': 'Unemployment',
    'visual merchandiser - nhân viên trưng bày': 'Others',  
    'alumni officer': 'Others',
    'không tiết lộ': 'Undisclosed',
    'phạm văn bạch': 'Undisclosed',
    'cabin crew': 'Others',
    'flight attendant': 'Others',
    'airport screening': 'Others',  
    'đi nghĩa vụ':'Others',
    'bartender':'Others',
    'cầu giấy': 'Others',
    'không cung cấp': 'Undisclosed',
})



In [25]:
result['Vị trí công việc'].describe()

count           724
unique           12
top       Developer
freq            144
Name: Vị trí công việc, dtype: object

In [26]:
result = result.drop_duplicates(subset="SĐT", keep='last')

In [27]:
result.dropna(inplace=True)

In [28]:
result.to_excel('data_output.xlsx', index=False)